import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { PDFDocument, rgb, StandardFonts } from 'https://esm.sh/pdf-lib@1.17.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface BillClassification {
  billId: string;
  introNumber: string;
  title: string;
  classification: string;
  reasoning: string;
  confidence: number;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Missing authorization' }), {
      status: 401,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    { global: { headers: { Authorization: authHeader } } }
  );

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    const { reportId } = await req.json();
    if (!reportId) {
      return new Response(JSON.stringify({ error: 'reportId is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Get report and verify ownership
    const { data: report, error: reportError } = await supabase
      .from('impact_reports')
      .select('*, policy_platforms(filename)')
      .eq('id', reportId)
      .eq('user_id', user.id)
      .single();

    if (reportError || !report) {
      return new Response(JSON.stringify({ error: 'Report not found' }), {
        status: 404,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    if (report.status !== 'complete' || !report.report_json) {
      return new Response(JSON.stringify({ error: 'Report is not ready' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Get user profile for display name
    const { data: profile } = await supabase
      .from('profiles')
      .select('display_name')
      .eq('id', user.id)
      .single();

    const results: BillClassification[] = report.report_json.results || [];
    const orgName =
      report.policy_platforms?.filename?.replace(/\.(pdf|txt)$/i, '') ||
      profile?.display_name ||
      'Organization';
    const analysisDate = new Date(report.created_at).toLocaleDateString(
      'en-US',
      { year: 'numeric', month: 'long', day: 'numeric' }
    );

    // Classify and sort by confidence descending
    const opportunities = results
      .filter((r) => r.classification === 'Opportunity')
      .sort((a, b) => b.confidence - a.confidence);
    const threats = results
      .filter((r) => r.classification === 'Threat')
      .sort((a, b) => b.confidence - a.confidence);
    const conflicts = results
      .filter((r) => r.classification === 'Conflict')
      .sort((a, b) => b.confidence - a.confidence);
    const neutralCount =
      results.length - opportunities.length - threats.length - conflicts.length;

    // --- PDF generation ---
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_WIDTH = 612; // US Letter
    const PAGE_HEIGHT = 792;
    const MARGIN = 50;
    const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
    const LINE_HEIGHT = 16;
    const FOOTER_Y = 30;

    let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    let y = PAGE_HEIGHT - MARGIN;

    /** Draw the footer on a given page. */
    function addFooter(p: typeof page) {
      p.drawText('Generated by Council Watch NYC — councilwatch.nyc', {
        x: MARGIN,
        y: FOOTER_Y,
        size: 8,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
    }

    /** Ensure there is enough vertical space; if not, finalize current page and start a new one. */
    function ensureSpace(needed: number) {
      if (y - needed < MARGIN + 40) {
        addFooter(page);
        page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        y = PAGE_HEIGHT - MARGIN;
      }
    }

    /** Draw text that wraps within maxWidth, advancing y downward. Returns lines used. */
    function drawWrappedText(
      text: string,
      x: number,
      maxWidth: number,
      size: number,
      f: typeof font,
      color = rgb(0.2, 0.2, 0.2)
    ): number {
      const words = text.split(' ');
      let line = '';
      let linesUsed = 0;

      for (const word of words) {
        const testLine = line ? `${line} ${word}` : word;
        const testWidth = f.widthOfTextAtSize(testLine, size);
        if (testWidth > maxWidth && line) {
          ensureSpace(LINE_HEIGHT);
          page.drawText(line, { x, y, size, font: f, color });
          y -= LINE_HEIGHT;
          linesUsed++;
          line = word;
        } else {
          line = testLine;
        }
      }

      if (line) {
        ensureSpace(LINE_HEIGHT);
        page.drawText(line, { x, y, size, font: f, color });
        y -= LINE_HEIGHT;
        linesUsed++;
      }

      return linesUsed;
    }

    // --- Page 1: Executive Summary ---
    page.drawText('COUNCIL WATCH NYC', {
      x: MARGIN,
      y,
      size: 10,
      font: fontBold,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= 24;

    page.drawText('Impact Analysis Report', {
      x: MARGIN,
      y,
      size: 24,
      font: fontBold,
      color: rgb(0, 0, 0),
    });
    y -= 28;

    page.drawText(`Organization: ${orgName}`, {
      x: MARGIN,
      y,
      size: 11,
      font,
      color: rgb(0.3, 0.3, 0.3),
    });
    y -= LINE_HEIGHT;

    page.drawText(`Analysis Date: ${analysisDate}`, {
      x: MARGIN,
      y,
      size: 11,
      font,
      color: rgb(0.3, 0.3, 0.3),
    });
    y -= 30;

    // Summary statistics
    page.drawText('EXECUTIVE SUMMARY', {
      x: MARGIN,
      y,
      size: 12,
      font: fontBold,
      color: rgb(0, 0, 0),
    });
    y -= 20;

    page.drawText(`Total Bills Analyzed: ${results.length}`, {
      x: MARGIN,
      y,
      size: 10,
      font,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= LINE_HEIGHT;

    page.drawText(
      `Opportunities: ${opportunities.length}  |  Threats: ${threats.length}  |  Conflicts: ${conflicts.length}  |  Neutral: ${neutralCount}`,
      {
        x: MARGIN,
        y,
        size: 10,
        font,
        color: rgb(0.2, 0.2, 0.2),
      }
    );
    y -= 30;

    // --- Classification sections ---
    function drawSection(
      title: string,
      items: BillClassification[],
      headerColor: ReturnType<typeof rgb>
    ) {
      ensureSpace(40);

      // Section header bar
      page.drawRectangle({
        x: MARGIN,
        y: y - 2,
        width: CONTENT_WIDTH,
        height: 22,
        color: headerColor,
      });
      page.drawText(title.toUpperCase(), {
        x: MARGIN + 8,
        y: y + 2,
        size: 11,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      y -= 30;

      if (items.length === 0) {
        page.drawText('No bills in this category.', {
          x: MARGIN + 8,
          y,
          size: 10,
          font,
          color: rgb(0.5, 0.5, 0.5),
        });
        y -= 20;
        return;
      }

      for (const item of items) {
        ensureSpace(60);
        const conf = `${Math.round(item.confidence * 100)}%`;

        page.drawText(`${item.introNumber} (${conf})`, {
          x: MARGIN + 8,
          y,
          size: 10,
          font: fontBold,
          color: rgb(0, 0, 0),
        });
        y -= LINE_HEIGHT;

        drawWrappedText(
          item.title,
          MARGIN + 8,
          CONTENT_WIDTH - 16,
          9,
          font,
          rgb(0.2, 0.2, 0.2)
        );
        drawWrappedText(
          item.reasoning,
          MARGIN + 8,
          CONTENT_WIDTH - 16,
          8,
          font,
          rgb(0.4, 0.4, 0.4)
        );
        y -= 8;
      }
    }

    drawSection(
      `Opportunities (${opportunities.length})`,
      opportunities,
      rgb(0.13, 0.55, 0.13)
    );
    drawSection(`Threats (${threats.length})`, threats, rgb(0.8, 0.15, 0.15));
    drawSection(
      `Conflicts (${conflicts.length})`,
      conflicts,
      rgb(0.85, 0.55, 0.0)
    );

    // Footer on the last page
    addFooter(page);

    // --- Save and upload ---
    const pdfBytes = await pdfDoc.save();
    const storagePath = `reports/${user.id}/${reportId}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from('policy-platforms')
      .upload(storagePath, pdfBytes, {
        contentType: 'application/pdf',
        upsert: true,
      });

    if (uploadError) throw uploadError;

    // Signed URL with 1-hour expiry
    const { data: signed, error: signError } = await supabase.storage
      .from('policy-platforms')
      .createSignedUrl(storagePath, 3600);

    if (signError) throw signError;

    return new Response(JSON.stringify({ url: signed.signedUrl }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
