import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { PDFDocument, rgb, StandardFonts } from 'https://esm.sh/pdf-lib@1.17.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) {
    return new Response(JSON.stringify({ error: 'Missing authorization' }), {
      status: 401,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    { global: { headers: { Authorization: authHeader } } }
  );

  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    const body = await req.json().catch(() => ({}));
    const targetUserId = body.userId || user.id;

    // Fetch brief preferences
    const { data: prefs } = await supabase
      .from('brief_preferences')
      .select('*')
      .eq('user_id', targetUserId)
      .single();

    const preferences = prefs || {
      include_watchlist: true,
      include_conflicts: true,
      include_workhorse: true,
      branding_org_name: null,
      branding_logo_url: null,
    };

    // Fetch watchlist items
    let watchlistItems: { item_type: string; item_value: string; item_label: string }[] = [];
    if (preferences.include_watchlist) {
      const { data } = await supabase
        .from('watchlist_items')
        .select('item_type, item_value, item_label')
        .eq('user_id', targetUserId);
      watchlistItems = data || [];
    }

    // Fetch static data from Supabase storage
    let conflictAlerts: { member: string; bill: string; description: string }[] = [];
    if (preferences.include_conflicts) {
      try {
        const { data: conflictData } = await supabase.storage
          .from('policy-platforms')
          .download('static/conflict-alerts.json');
        if (conflictData) {
          const text = await conflictData.text();
          conflictAlerts = JSON.parse(text);
        }
      } catch {
        // Static file may not exist yet
      }
    }

    let workhorseRankings: { member: string; score: number; rank: number }[] = [];
    if (preferences.include_workhorse) {
      try {
        const { data: workhorseData } = await supabase.storage
          .from('policy-platforms')
          .download('static/workhorse-index.json');
        if (workhorseData) {
          const text = await workhorseData.text();
          workhorseRankings = JSON.parse(text);
        }
      } catch {
        // Static file may not exist yet
      }
    }

    // --- PDF generation ---
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_WIDTH = 612; // US Letter
    const PAGE_HEIGHT = 792;
    const MARGIN = 50;
    const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
    const LINE_HEIGHT = 16;
    const FOOTER_Y = 30;

    let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    let y = PAGE_HEIGHT - MARGIN;

    const orgName = preferences.branding_org_name || 'Council Watch NYC';
    const briefDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    /** Draw the footer on a given page. */
    function addFooter(p: typeof page) {
      p.drawText('Generated by Council Watch NYC — councilwatch.nyc', {
        x: MARGIN,
        y: FOOTER_Y,
        size: 8,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
    }

    /** Ensure there is enough vertical space; if not, finalize current page and start a new one. */
    function ensureSpace(needed: number) {
      if (y - needed < MARGIN + 40) {
        addFooter(page);
        page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        y = PAGE_HEIGHT - MARGIN;
      }
    }

    /** Draw text that wraps within maxWidth, advancing y downward. Returns lines used. */
    function drawWrappedText(
      text: string,
      x: number,
      maxWidth: number,
      size: number,
      f: typeof font,
      color = rgb(0.2, 0.2, 0.2)
    ): number {
      const words = text.split(' ');
      let line = '';
      let linesUsed = 0;

      for (const word of words) {
        const testLine = line ? `${line} ${word}` : word;
        const testWidth = f.widthOfTextAtSize(testLine, size);
        if (testWidth > maxWidth && line) {
          ensureSpace(LINE_HEIGHT);
          page.drawText(line, { x, y, size, font: f, color });
          y -= LINE_HEIGHT;
          linesUsed++;
          line = word;
        } else {
          line = testLine;
        }
      }

      if (line) {
        ensureSpace(LINE_HEIGHT);
        page.drawText(line, { x, y, size, font: f, color });
        y -= LINE_HEIGHT;
        linesUsed++;
      }

      return linesUsed;
    }

    // --- Header ---
    page.drawText(orgName.toUpperCase(), {
      x: MARGIN,
      y,
      size: 10,
      font: fontBold,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= 24;

    page.drawText('Weekly Legislative Brief', {
      x: MARGIN,
      y,
      size: 24,
      font: fontBold,
      color: rgb(0, 0, 0),
    });
    y -= 28;

    page.drawText(`Prepared: ${briefDate}`, {
      x: MARGIN,
      y,
      size: 11,
      font,
      color: rgb(0.3, 0.3, 0.3),
    });
    y -= 30;

    // --- Section: Watchlist Activity ---
    if (preferences.include_watchlist) {
      ensureSpace(40);

      page.drawRectangle({
        x: MARGIN,
        y: y - 2,
        width: CONTENT_WIDTH,
        height: 22,
        color: rgb(0.13, 0.4, 0.67),
      });
      page.drawText('WATCHLIST ACTIVITY', {
        x: MARGIN + 8,
        y: y + 2,
        size: 11,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      y -= 30;

      if (watchlistItems.length === 0) {
        page.drawText('No items on your watchlist.', {
          x: MARGIN + 8,
          y,
          size: 10,
          font,
          color: rgb(0.5, 0.5, 0.5),
        });
        y -= 20;
      } else {
        for (const item of watchlistItems) {
          ensureSpace(40);
          page.drawText(`${item.item_type.toUpperCase()}: ${item.item_value}`, {
            x: MARGIN + 8,
            y,
            size: 10,
            font: fontBold,
            color: rgb(0, 0, 0),
          });
          y -= LINE_HEIGHT;
          if (item.item_label) {
            drawWrappedText(
              item.item_label,
              MARGIN + 8,
              CONTENT_WIDTH - 16,
              9,
              font,
              rgb(0.3, 0.3, 0.3)
            );
          }
          y -= 4;
        }
      }

      y -= 10;
    }

    // --- Section: Conflict Alerts ---
    if (preferences.include_conflicts) {
      ensureSpace(40);

      page.drawRectangle({
        x: MARGIN,
        y: y - 2,
        width: CONTENT_WIDTH,
        height: 22,
        color: rgb(0.85, 0.55, 0.0),
      });
      page.drawText('CONFLICT ALERTS', {
        x: MARGIN + 8,
        y: y + 2,
        size: 11,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      y -= 30;

      if (conflictAlerts.length === 0) {
        page.drawText('No conflict alerts at this time.', {
          x: MARGIN + 8,
          y,
          size: 10,
          font,
          color: rgb(0.5, 0.5, 0.5),
        });
        y -= 20;
      } else {
        for (const alert of conflictAlerts) {
          ensureSpace(50);
          page.drawText(`${alert.member} — ${alert.bill}`, {
            x: MARGIN + 8,
            y,
            size: 10,
            font: fontBold,
            color: rgb(0, 0, 0),
          });
          y -= LINE_HEIGHT;
          drawWrappedText(
            alert.description,
            MARGIN + 8,
            CONTENT_WIDTH - 16,
            9,
            font,
            rgb(0.4, 0.4, 0.4)
          );
          y -= 4;
        }
      }

      y -= 10;
    }

    // --- Section: WorkHorse Rankings ---
    if (preferences.include_workhorse) {
      ensureSpace(40);

      page.drawRectangle({
        x: MARGIN,
        y: y - 2,
        width: CONTENT_WIDTH,
        height: 22,
        color: rgb(0.13, 0.55, 0.13),
      });
      page.drawText('WORKHORSE RANKINGS', {
        x: MARGIN + 8,
        y: y + 2,
        size: 11,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      y -= 30;

      if (workhorseRankings.length === 0) {
        page.drawText('No workhorse data available.', {
          x: MARGIN + 8,
          y,
          size: 10,
          font,
          color: rgb(0.5, 0.5, 0.5),
        });
        y -= 20;
      } else {
        // Show top 15
        const topRankings = workhorseRankings
          .sort((a, b) => a.rank - b.rank)
          .slice(0, 15);

        for (const entry of topRankings) {
          ensureSpace(20);
          page.drawText(
            `#${entry.rank}  ${entry.member}  —  Score: ${entry.score}`,
            {
              x: MARGIN + 8,
              y,
              size: 10,
              font,
              color: rgb(0.2, 0.2, 0.2),
            }
          );
          y -= LINE_HEIGHT;
        }
      }
    }

    // Footer on the last page
    addFooter(page);

    // --- Save and upload ---
    const pdfBytes = await pdfDoc.save();
    const dateSlug = new Date().toISOString().split('T')[0];
    const storagePath = `briefs/${targetUserId}/${dateSlug}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from('document-vault')
      .upload(storagePath, pdfBytes, {
        contentType: 'application/pdf',
        upsert: true,
      });

    if (uploadError) throw uploadError;

    // Update last_generated_at
    await supabase
      .from('brief_preferences')
      .upsert({ user_id: targetUserId, last_generated_at: new Date().toISOString() });

    // Signed URL with 1-hour expiry
    const { data: signed, error: signError } = await supabase.storage
      .from('document-vault')
      .createSignedUrl(storagePath, 3600);

    if (signError) throw signError;

    return new Response(JSON.stringify({ url: signed.signedUrl }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
